name: My Workflow

on: [push]

jobs:
  hello-nedap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check checkout
        run: cat pom.xml


#      - name: Hello Nedap
#        run: echo "Hello Nedap"
#
#      - name: Something else
#        run: echo